# -*- coding: utf-8 -*-
"""backpropagation part two.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dl8yqfYJ2F5vStLq7qI-ydlqcvjHKuNp

# unit 1.4 - Back-propagation

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://githubtocolab.com/culurciello/deep-learning-course-source/blob/main/source/lectures/14-backpropagation.ipynb)

Back-propagation is an optimization algorithm commonly used in training artificial neural networks. It's a supervised learning algorithm that adjusts the weights of the network to minimize the error between predicted and actual outputs.

Back-propagation is an algorithm that is based on the concept of gradient-descent.

## Gradient descent

<!-- Recall we talked about:
- [loss](https://pytorch.org/docs/stable/nn.html#loss-functions)
- [optimizer](https://pytorch.org/docs/stable/optim.html) -->

When we train a neural network we want to minimize the error between the samples from the dataset and the output of the neural networks.

Training a neural network means minimizing the loss function over the dataset.

This is not much different from when you play basketball: you (the neural network) want to get the ball in the basket.

![](https://github.com/culurciello/deep-learning-course-source/blob/main/source/lectures/images/gd1.png?raw=1)

The error function is how much you are off.

![](https://github.com/culurciello/deep-learning-course-source/blob/main/source/lectures/images/gd2.png?raw=1)

The correction (change in the neural network weights) is how much you have to correct to get the right output (the ball in the basket).

![](https://github.com/culurciello/deep-learning-course-source/blob/main/source/lectures/images/gd3.png?raw=1)

The you just try again...

![](https://github.com/culurciello/deep-learning-course-source/blob/main/source/lectures/images/gd4.png?raw=1)

and again...

![](https://github.com/culurciello/deep-learning-course-source/blob/main/source/lectures/images/gd5.png?raw=1)

until your error is $~0$ (the ball IS IN the basket!)

This whole process is called "Gradient Descent" and it is the way to find a good set of weights for your neural network that minimizes the loss function.

![](https://github.com/culurciello/deep-learning-course-source/blob/main/source/lectures/images/gradient-descent.png?raw=1)

## gradient descent code example

We can now see an example of how this is implemented in python.

Here is a possible loss function f(x):

$f(x) = x³-4x²+6$
"""

import numpy as np
import matplotlib.pyplot as plt

f_x = lambda x: (x**3)-4*(x**2)+6

x = np.linspace(-1,4,500) # plot the curve
plt.plot(x, f_x(x))
plt.show()

"""Gradient descent is the way we can find the minimum of a function like f(x).

Here is some code implementing gradient descent and an helper function to visualize the algorithm.
"""

def plot_gradient(x, y, x_vis, y_vis):
    plt.subplot(1,2,2)
    plt.scatter(x_vis, y_vis, c = "b")
    plt.plot(x, f_x(x), c = "r")
    plt.title("Gradient Descent")
    plt.show()
    plt.subplot(1,2,1)
    plt.scatter(x_vis, y_vis, c = "b")
    plt.plot(x,f_x(x), c = "r")
    plt.xlim([2.0,3.0])
    plt.title("Zoomed in Figure")
    plt.show()

def gradient_desc(x_start, steps, learning_rate, delta=0.01):

    # These x and y value lists will be used later for visualization.
    x_grad = [x_start]
    y_grad = [f_x(x_start)]
    # Keep looping until number of iterations
    for i in range(steps):
        # compute the derivative:
        x_start_derivative = (f_x(x_start)-f_x(x_start-delta))/delta # derivative approximation

        # next point is - learning_rate * derivative:
        x_start -= (learning_rate * x_start_derivative)

        # update the lists for visualization:
        x_grad.append(x_start)
        y_grad.append(f_x(x_start))

    print ("Local minimum occurs at: {:.2f}".format(x_start))
    print ("Number of steps: ",len(x_grad)-1)
    plot_gradient(x, f_x(x) ,x_grad, y_grad)

"""We can now try this on our loss function f(x) and its derivative.

We do this starting at value x = 0.5, using 100 steps, and with a learning-rate of 0.05
"""

gradient_desc(0.5, 100, 0.05)

"""Note this notebook was inspired by [this post](https://machinelearningmind.com/2019/10/06/gradient-descent-introduction-and-implementation-in-python/).

## A numerical example of neural network training

Let's consider a simple two-layer neural network with two inputs (x1 and x2), two neurons in the first layer (hidden layer), and two neurons in the second layer (output layer). We'll use a mean squared error (MSE) loss function.

Here's the architecture:
- Inputs: x1, x2
- Hidden layer neurons: h1, h2
- Output layer neurons: o1, o2

![](https://github.com/culurciello/deep-learning-course-source/blob/main/source/lectures/images/backpropagation.png?raw=1)

The forward pass can be expressed as follows:

$h_1 = w_{11} \cdot x_1 + w_{21} \cdot x_2 + b_1$

$h_2 = w_{12} \cdot x_1 + w_{22} \cdot x_2 + b_2$

$o_1 = w_{31} \cdot h_1 + w_{41} \cdot h_2 + b_3$

$o_2 = w_{32} \cdot h_1 + w_{42} \cdot h_2 + b_4$

Here, $w$ represents weights, $b$ represents biases, and the subscripts denote the connection between neurons.

Let's assume the target outputs are $y_1$ and $y_2$. The MSE loss is given by:
$L = \frac{1}{2} \sum_{i=1}^{2} (y_i - o_i)^2$

Now, we want to minimize this loss using backpropagation.

### 1. Compute the error terms at the output layer:

$ \delta_{o1} = (o_1 - y_1) \cdot \sigma'(o_1)$

$ \delta_{o2} = (o_2 - y_2) \cdot \sigma'(o_2)$

Here, $\sigma'$ is the derivative of the activation function used in the output layer (for simplicity, assume a linear activation, so $\sigma'(x) = 1$).

### 2. Compute the error terms at the hidden layer:

$ \delta_{h1} = (\delta_{o1} \cdot w_{31} + \delta_{o2} \cdot w_{32}) \cdot \sigma'(h1)$

$ \delta_{h2} = (\delta_{o1} \cdot w_{41} + \delta_{o2} \cdot w_{42}) \cdot \sigma'(h2)$


### 3. Update the weights and biases using the error terms and learning rate ($\alpha$):

$ w_{31}^{new} = w_{31} - \alpha \cdot \delta_{o1} \cdot h_1$

$ w_{41}^{new} = w_{41} - \alpha \cdot \delta_{o1} \cdot h_2$

$ w_{32}^{new} = w_{32} - \alpha \cdot \delta_{o2} \cdot h_1$

$ w_{42}^{new} = w_{42} - \alpha \cdot \delta_{o2} \cdot h_2$

$ w_{11}^{new} = w_{11} - \alpha \cdot \delta_{h1} \cdot x_1$

$ w_{21}^{new} = w_{21} - \alpha \cdot \delta_{h1} \cdot x_2$

$ w_{12}^{new} = w_{12} - \alpha \cdot \delta_{h2} \cdot x_1$

$ w_{22}^{new} = w_{22} - \alpha \cdot \delta_{h2} \cdot x_2$


### 4. Update the biases similarly:

$ b_3^{new} = b_3 - \alpha \cdot \delta_{o1}$

$ b_4^{new} = b_4 - \alpha \cdot \delta_{o2}$

$ b_1^{new} = b_1 - \alpha \cdot \delta_{h1}$

$ b_2^{new} = b_2 - \alpha \cdot \delta_{h2}$

This process is repeated iteratively until the network converges to a solution that minimizes the error. The learning rate ($\alpha$) is a hyperparameter that determines the step size during weight and bias updates. Adjustments may be needed based on the specific problem and dataset.
"""

import numpy as np

# ── Activation Functions ──────────────────────────────────────────
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_deriv(x):
    s = sigmoid(x)
    return s * (1 - s)

# ── Network Initialization ────────────────────────────────────────
np.random.seed(42)

# Weights: hidden layer (input → hidden)
w11, w21 = 0.5, 0.3   # x1→h1, x2→h1
w12, w22 = 0.4, 0.6   # x1→h2, x2→h2

# Weights: output layer (hidden → output)
w31, w41 = 0.7, 0.2   # h1→o1, h2→o1
w32, w42 = 0.1, 0.8   # h1→o2, h2→o2

# Biases
b1, b2 = 0.1, 0.1     # hidden layer biases
b3, b4 = 0.1, 0.1     # output layer biases

# ── Input and Target ──────────────────────────────────────────────
x1, x2 = 1.0, 0.5
y1, y2 = 0.8, 0.3

alpha = 0.1   # learning rate

# ── Training Loop ─────────────────────────────────────────────────
for epoch in range(1000):

    # ── FORWARD PASS ──────────────────────────────────────────────
    # Hidden layer pre-activation
    h1_in = w11*x1 + w21*x2 + b1
    h2_in = w12*x1 + w22*x2 + b2

    # Hidden layer output (sigmoid)
    h1 = sigmoid(h1_in)
    h2 = sigmoid(h2_in)

    # Output layer (linear activation)
    o1 = w31*h1 + w41*h2 + b3
    o2 = w32*h1 + w42*h2 + b4

    # MSE Loss
    L = 0.5 * ((y1 - o1)**2 + (y2 - o2)**2)

    # ── BACKPROPAGATION ───────────────────────────────────────────
    # Step 1: Output layer error terms (σ'(o) = 1, linear activation)
    d_o1 = (o1 - y1) * 1.0    # δ_o1
    d_o2 = (o2 - y2) * 1.0    # δ_o2

    # Step 2: Hidden layer error terms
    d_h1 = (d_o1*w31 + d_o2*w32) * sigmoid_deriv(h1_in)   # δ_h1
    d_h2 = (d_o1*w41 + d_o2*w42) * sigmoid_deriv(h2_in)   # δ_h2

    # Step 3: Update output layer weights
    w31 -= alpha * d_o1 * h1
    w41 -= alpha * d_o1 * h2
    w32 -= alpha * d_o2 * h1
    w42 -= alpha * d_o2 * h2

    # Update hidden layer weights
    w11 -= alpha * d_h1 * x1
    w21 -= alpha * d_h1 * x2
    w12 -= alpha * d_h2 * x1
    w22 -= alpha * d_h2 * x2

    # Step 4: Update biases
    b3 -= alpha * d_o1
    b4 -= alpha * d_o2
    b1 -= alpha * d_h1
    b2 -= alpha * d_h2

    if epoch % 100 == 0:
        print(f"Epoch {epoch:4d} | Loss: {L:.6f} | o1={o1:.4f} o2={o2:.4f}")

print(f"\nFinal Output: o1={o1:.4f} (target: {y1}), o2={o2:.4f} (target: {y2})")
print(f"Final Loss  : {L:.8f}")

"""# **ALTERNATIVE**"""

import torchvision.transforms as transforms
from torchvision.datasets import FashionMNIST
from torch.utils.data import DataLoader

# ✅ প্রথমে transform define করুন
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.2860,), (0.3530,))  # FashionMNIST-এর mean ও std
])

# তারপর dataset load করুন
train_dataset = FashionMNIST(root="../data/", train=True,  download=True, transform=transform)
test_dataset  = FashionMNIST(root="../data/", train=False, download=True, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader  = DataLoader(test_dataset,  batch_size=64, shuffle=False)

print(f"Train size : {len(train_dataset)}")   # 60,000
print(f"Test size  : {len(test_dataset)}")    # 10,000
print(f"Classes    : {train_dataset.classes}")

from torchvision.datasets import FashionMNIST

train_dataset = FashionMNIST(root="../data/", train=True, download=True, transform=transform)
test_dataset  = FashionMNIST(root="../data/", train=False, download=True, transform=transform)

from torchvision.datasets import CIFAR10
from torchvision import transforms

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))  # RGB তিনটি channel
])

train_dataset = CIFAR10(root="../data/", train=True,  download=True, transform=transform)
test_dataset  = CIFAR10(root="../data/", train=False, download=True, transform=transform)

import torch
import torch.nn as nn
import torchvision.transforms as transforms
from torchvision.datasets import FashionMNIST
from torch.utils.data import DataLoader

# ── Transform & Dataset ───────────────────────────────────────────
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.2860,), (0.3530,))
])

test_dataset = FashionMNIST(root="../data/", train=False, download=True, transform=transform)
test_loader  = DataLoader(test_dataset, batch_size=64, shuffle=False)

# ── Simple Neural Network (2-layer) ──────────────────────────────
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(28*28, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 10)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = x.view(-1, 28*28)  # flatten
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        return self.fc3(x)

# ── Training ──────────────────────────────────────────────────────
train_dataset = FashionMNIST(root="../data/", train=True, download=True, transform=transform)
train_loader  = DataLoader(train_dataset, batch_size=64, shuffle=True)

model     = SimpleNN()
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epoch in range(5):
    model.train()
    total_loss = 0
    for images, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(images)
        loss    = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch [{epoch+1}/5] | Loss: {total_loss/len(train_loader):.4f}")

# ── Evaluation ────────────────────────────────────────────────────
model.eval()
correct = 0
total   = 0

class_names = test_dataset.classes
class_correct = [0] * 10
class_total   = [0] * 10

with torch.no_grad():
    for images, labels in test_loader:
        outputs    = model(images)
        _, predicted = torch.max(outputs, 1)
        total   += labels.size(0)
        correct += (predicted == labels).sum().item()

        for i in range(len(labels)):
            class_correct[labels[i]] += (predicted[i] == labels[i]).item()
            class_total[labels[i]]   += 1

# Overall accuracy
print(f"\n✅ Overall Accuracy: {100 * correct / total:.2f}%")

# Per-class accuracy
print("\n📊 Per-Class Accuracy:")
for i in range(10):
    acc = 100 * class_correct[i] / class_total[i]
    print(f"  {class_names[i]:<15} : {acc:.2f}%")